---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdDRENDQS9DZ0F3SUJBZ0lKQVBndWxSYnZXRVc3TUEwR0NTcUdTSWIzRFFFQkN3VUFNSEl4Q3pBSkJnTlYKQkFZVEFsTkZNUkF3RGdZRFZRUUlEQWRJWVd4c1lXNWtNUkF3RGdZRFZRUUhEQWRXWVhKaVpYSm5NUll3RkFZRApWUVFLREExaWJHbHdZbXh2Y0MxdWIyUmxNUkV3RHdZRFZRUUxEQWhpYkdsd1lteHZjREVVTUJJR0ExVUVBd3dMCllteHBjR0pzYjNBdFkyRXdIaGNOTWpVeE1ESTRNVEV4TlRNeVdoY05Nall4TURJNE1URXhOVE15V2pCME1Rc3cKQ1FZRFZRUUdFd0pUUlRFUU1BNEdBMVVFQ0F3SFNHRnNiR0Z1WkRFUU1BNEdBMVVFQnd3SFZtRnlZbVZ5WnpFVwpNQlFHQTFVRUNnd05ZbXhwY0dKc2IzQXRibTlrWlRFUk1BOEdBMVVFQ3d3SVlteHZjR0pzYjNBeEZqQVVCZ05WCkJBTU1EV0pzYVhCaWJHOXdMVzV2WkdVd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUMKQVFDd0RnY0NUejlnb0NBYXp4dU5BYXZGMzVXNjdqUU5sVlNGR0F4MG9FUVltNjJ2ek44aVNnU0FOLzhWUjJNaQp2dDV0aU0rU2wyajJ2SWY2WE5IaXdJTEpIcXJPaTZhT05YQmN4S1VDQkNoenYxck85NUNmOUZQUFBLMS9BR0liCmxsU2hXUGMvUTM3RGZMblRSWWIrSGRVS281aGRKcU4rTmRwMFY0bkxPdjdxdFM4QVNPNjd5NTBxeE9KaFA1YVMKM2RObDZzUldXdTJFRVhEVjY0aTY5NDVlL0lrQjRNUE9mRTloVFk2TTRzWkRlUy9oaVFOVkVZTkVwbVZTRVZRbgpaZjZvNWRIZC82a2dFQ3FzV0lCeTkvUWVtMW94ejdBc2hBQUoveWJsMXozVUNZS3RWNWwwOUxyRFEzaW0vdDBuCk4yNkFreisrWjJobnJ1R1dRTkdvKzRNWVd0Z2FEWFU1cjA0cHlaYi9QTkxyaVBLRDFjS1BIMGEreWhmK3M0aUkKVW5KM0lXZTNPK1lwT2lFSHJ2RHFmVG5rU1kweDJMNStmcGVSencvVWJZc2ZGY2p1ZTdlSmtJK3BKUFU2OGRrTApSTERHb29UOE56QU1tQmNLMU1ob0drZWJzbGFoMmI3b0JzdFBDNmNaaDBDOHlYV0YremwwcU9TYVByTzE0amErClZuWVFGYnFEc2NEd0l5RFJ1Zmd0UFhOMzY5RWFISW9Ja1lGNng1YVZMYWVlWDVHdG96eXZBN0NWSGNTMUtraEsKeVhnYndBMkRXaU5FWFFsZml1Q2FOVnRLTVdPV053SERBMWZYblpvTFdEUG9qajFFNm1sSzJnakRvS1Z0c2FNYwoxSDRxa29GaXNyVmdVNThvU0xPb09KVGhzVmdPRnJiWkJ2aTl2UDYrWmswUEl3SURBUUFCbzRHZU1JR2JNQWtHCkExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQWlCZ05WSFJFRUd6QVpnZ2xzYjJOaGJHaHZjM1NDQm1KaWJtOWtaWWNFZndBQUFUQWRCZ05WSFE0RQpGZ1FVU0lBcEVqU0ptbzBWUzE0Q0pYcDcvUnEramYwd0h3WURWUjBqQkJnd0ZvQVVQVk9qcXZ2M3JFVHBHVlVxCi9MZHdxejNCanVRd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFMWUlyR01WdVEvTHE3YzJwWkdYeE04am1rZlAKK3B3UjRyNDl0WXZ6enJMc3dvWmZVMWxRWk44c3I3MWh0YmVUTW80Vm5jQlNCUnpoQm51ZlFXWnJyZGRWTEZKRQovUjRyNWlkN05VQVozc2ZqOFkvZUN6REtiWUFvWjN3YllhbFA2aGp2RUovVzNrMkJGOVR5R25wSENHRk56aVY4ClVhRWJGam5mZFZPUmwyLzg1b2cvMzdxblFYVG9aQVFvKzVraWV1aC94RnNRb293Tkt2eVdsVnY5Wk1hVmZ2ZTgKaU9EQ3dpRVBiN0tTZ0ZSYXZKWHdPZjE5OHlGUWtIcXVPV2VYaGZNWmhGeXlWWGhCd0l3SkJXcUI1eFFZS2tReQozWktodm9sK3JpTXExVW5WNjhWbUxDbU5TTkkwaXdyMXZUMWZvQ1dUdStOU0VaZ2tiWjJpOExuYkMxS1lEUS9BCmZWRXdxamZYOGtJT3lJc3VFNkRsOFVVU21YSVl2YlVrejNJYkRwRFFaZ21PR2d4bmJYY1FoYkVxbjZGNDJiWTQKaFphb1FjTlhGSlBPYm1vaG9YMWczRU9Hc0F2ZXVLMEtzdlJTWUdmcE5PUWt3WmJMSWwyS0t3dWNicUdXeGxGcQpUcklMZnV3Y0xOMTZpU0I2TVBENWt0eEJiblF5RjFRWlhxb0wwZUpZVy91OG1oUmc2NlUxVDNWbUc2clFOcXlsCnNPWTMra3RUcXhDalpKVkh5VG1yTDU1Z3c1WDFXSFBwYkNCWFZmZjRSc1oxWXlCZXFZYjBFbVpWelYzQ1VmOXMKNlJCUjJ1WE94SU5Qd3YxcVhEa01mTkVZeVBsTEgyR1VYV0FNcWVORzVwdGoxamtvT3dHRWthWmxwTStadjFyQQpSWGhNT05QY1YzRzBURjlGCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Mwd2dna3BBZ0VBQW9JQ0FRQ3dEZ2NDVHo5Z29DQWEKenh1TkFhdkYzNVc2N2pRTmxWU0ZHQXgwb0VRWW02MnZ6TjhpU2dTQU4vOFZSMk1pdnQ1dGlNK1NsMmoydklmNgpYTkhpd0lMSkhxck9pNmFPTlhCY3hLVUNCQ2h6djFyTzk1Q2Y5RlBQUEsxL0FHSWJsbFNoV1BjL1EzN0RmTG5UClJZYitIZFVLbzVoZEpxTitOZHAwVjRuTE92N3F0UzhBU082N3k1MHF4T0poUDVhUzNkTmw2c1JXV3UyRUVYRFYKNjRpNjk0NWUvSWtCNE1QT2ZFOWhUWTZNNHNaRGVTL2hpUU5WRVlORXBtVlNFVlFuWmY2bzVkSGQvNmtnRUNxcwpXSUJ5OS9RZW0xb3h6N0FzaEFBSi95YmwxejNVQ1lLdFY1bDA5THJEUTNpbS90MG5OMjZBa3orK1oyaG5ydUdXClFOR28rNE1ZV3RnYURYVTVyMDRweVpiL1BOTHJpUEtEMWNLUEgwYSt5aGYrczRpSVVuSjNJV2UzTytZcE9pRUgKcnZEcWZUbmtTWTB4Mkw1K2ZwZVJ6dy9VYllzZkZjanVlN2VKa0krcEpQVTY4ZGtMUkxER29vVDhOekFNbUJjSwoxTWhvR2tlYnNsYWgyYjdvQnN0UEM2Y1poMEM4eVhXRit6bDBxT1NhUHJPMTRqYStWbllRRmJxRHNjRHdJeURSCnVmZ3RQWE4zNjlFYUhJb0lrWUY2eDVhVkxhZWVYNUd0b3p5dkE3Q1ZIY1MxS2toS3lYZ2J3QTJEV2lORVhRbGYKaXVDYU5WdEtNV09XTndIREExZlhuWm9MV0RQb2pqMUU2bWxLMmdqRG9LVnRzYU1jMUg0cWtvRmlzclZnVTU4bwpTTE9vT0pUaHNWZ09GcmJaQnZpOXZQNitaazBQSXdJREFRQUJBb0lDQURDaTMyclM2OFpNMWpHeHo0R24yWVZqCm5DQzFGNm84KzhsOCtFdnJ6b1FoMWR6QU0xQnN0RXVickp0N1NqYmFGZWFhcWdWc1VMSUJLV3VQNHVmS21SYm8Kb3ZWR2ZTL0NNWlZmT2RxUnZYOGtlUGkrU2JUMnNZU0oxY0JGSWRWUE5YZ1JkTlNFVit1M2REcWFkWTJVUGp1ZgpNRU5qbmowS3Nadjhadk8vQzVkWmtHOTZ0b0VvNGZWanlNcG0zN2taRVFLUjFjV3BmdjVDTnpMUnk4Y2pCckRWCkFTQ0VzSE5Gd2tRMlFkQklBYys0RmZNdmY3MHJobUVidXRmdU01cGl3ZlIwOFFKc1U1T3BBN0R6RGlFMHdMc0gKM2VYdTQxT1k3ODNUTURMRXdLN29KYkt2aFpSYTI1Ri8vVC9kSHNscnRkcE5VNG5OVlhsM1JaalZ0VllDalpkaQppRUNVV2YxNnlRTXo3WksyM0Z5QkkrZFVsR1lUVUVMUVAzRWlMa25iZ3JneVlVdkk2MVl0NVl6SmJxWXk1VzIwCkZwM3djd3lGY1dxYjVTQ1dYdlBNOUt1WStBR05BampUd2g3KzMyb2FvOGE0NlNpeDBMQlBFcnR5N3VvUnJpTmYKR2FWQTJSNWFQY2hOQnBDK2pJbGNBRWxIZ3NKcWtiMlpqRjNVUElGVWRSS09xdmJabVZuTy92NWRwVkJ6WHFITwphUWowQ044a1RHRXNZS1VIOElHV2haRU5CcWRiZFhGVTc2UTlLQi81V2UrUXVSNC91eWhYTFJMckpmcHVSVXN1ClJ2VktMWmUxMEVIWDI2Q3IyVEk0VElhOHIybjd2UHhJV29BYlBwTkw1YW1PaXBIYlVlcVQ5bXhBcDlkT1hEVzEKOVlLdEhVMDJTNWZhS3AyanVNcHhBb0lCQVFEWUZHTGpwYklyd1pMUnNaY216NGN6WUd6K0ZjZmV2eTFHczUvbgp1a1VENWMrSHlaQ0wveElKNGNtWEpjWnFRK0ZESjdaMUFrSzR5TE1EaCswSThSZll5cFlqa2tqL28wUm5qbXpRCmRTVi9xOE5nYzlzU2lIQ3lPWENIOTI3WEU5QmdzWTlvQzZ1a0dadm5zanhTZ1F0Y2dJNFV3RSs2VGxEU0hlUFIKRmxBL0llYVJ2Q1NGdkRyMmtWWW8vVkN0ZUNoL0RHUTFKMXlRUmo1L1ZlKzBTcHBaTnhGZXFpdWdhVXFORUlNbAo4Q1RFUGJ6VzNSb08vYWdNeDFnbDVQUGpBdXdxNGJQeWxicHkxQXFjUU5UMStOQ1JnZ1lvcjMvMVRWVW9OMkRsCjJpRzg1Nkl5K0huZUxPS1Y4ejNubGtvWEJhTDVtSld5aThrUlY3aFdGcmxZV3Z0YkFvSUJBUURRbEtTSVlpSHYKNk1DeUVDZjB4UWZQazZOUVlDVlQ3SzROMzRJR0J2WjF6cTFodnFSVWJsWDNNbSs1UTJCWUZOQlhRYzZaM01UNgpUMUNoTTBHdXJCRnl6WCtrelhyQVBQcHNaVTlUU0pnU0t1NHVIZzhMY0NwUkZqSmRFbVh5UDljdHhhVWZjYXJFCjlxTXhpL05ScVJ6Nm9NTWlOb3dRQm51M0V1aldaa3oyVmNZZDdQVmJOc2p2djQxOGlkTytZeHVMcW4ySEdLWGEKQTdkWUJWcEk2Ym9hRTZLTk9mcVpMcGVVUFR3NmpRc2VzZWpITnoyK3lrUlJNdzIyTjU5T0NWVjZHUWVZSVlURApJclZEVlAzR2pkM2s2TmhsYTEwMW1RZDhaRjgwdjdZdXVLR2Z0cHAvWXdsVWc2Z2E4N1pxc25kUkZ4MFJhSnVtCjFMcGhRZ2s4TFMzWkFvSUJBUUNSNklJMk1vY3pZTTBoYUFnbkh1K3UwNmdGa3ZPYUNBSXN3ZEp5aWFkYzBHdm8KeDBVaUk2VXNveGliUmRqTG5QYVpnRkdHaFhaRWpOSEV5cDVXOFdZbTcvV2VJNFBEaTUzL1IzOVc3Q1BjS0VJUAorV3V2QWc4SGFoNEEwaVk0ZVpxMkVIQkQwODJkUytXbytRUWV1aURQMzhjUllDTDJMVGdLQ2tEeHlWMTZwQXVyCjBSM2dhSkJ3T3dleE9neW1kb0x4OTQ0YkRtOUV4UW9pdGdiYytadHNMdkU5dVM4b2JMRDR2SE95eEl3dkwzazYKcGFhWkJOUGJmU2lhdmhXcDd5bEdjNDR0ZXNtaURHajF4aG1IMXZJUHIzczFNZnozeWJaOUo1ZjQzZWoyUkh1VQphNUR2WStQRldiRXRscUNGRnp0THk2c2FHNlkwWGNXTjdGNVB1WEFOQW9JQkFRQ2RjZmFZdEdxbHErMzQrMVVOCjRNUzZuZGxEVExBZ242SHErdkl0Rm9obitQREx2WnBSMlUrdTN6V1NoUmR1cFpkMnBrZ0x3S2czd2pNODIzSVQKSmZPdDB3MHRHNll6QWxTT0NoTk03SmxON1hZSS9jdWhlTE9ZcmNhcWxyNjVsQk1iaS92T3RvQ1BXUlZxeXhlSwpacnRuUEg3UGpway9aNFZ2ZGlpbjNtVHQ5V1V0SmJjM2VTMUlQREhTOWo4TmtjWXpNU2k4RjVEcDlyQXBFekZKCnBKUkVKdG9tL01MN2FqNGxPZXdDem9DOFZOTS92YVV3SllKWVFNOXk0cDJ2ekQvbmdJbEkvdFEyY0RhZmNzSjEKWkpWQXU3ck5JN1FpUnpkdFlGNjFkSmxTdnkvUlhZZFY3UzRYeTZIVFpuQW1ManoreXhHNEdGeVdIREhzUkdxdwpML0pSQW9JQkFFS0lhZ2RlbXMvQTVtQzdadnlEOENWcVZqYTRzeVdmNmZpWEVwUHJvK1pnQWNHejQvSG9HQUwzCnVYWmxxZjFhTWsxN3NUQ2hHRHZsNitiWUkyVm5aUEl6U3V0SVpGc0paZVNWMHJKMFZ4K3ZSekpPeHdBaldNK3kKYjBudFZPbmlVQlBqSjdjMTVvRVFUUXBYRUF3ZDlGQ3lrTEJvOG43Z3NMVElIb20ybDlEYzNGaFZZb1p6UWFhUQoxNnpneDR5V2IzcDZPNHhnQS9iYWRYSExBbHd5MEpVQ01nZFhlYXNWM2VqYkpyYTRqN2NwMkcydVVVM3VLcFNCCjhYbTlRZXdvWHpCTmc5TWVpS1FiMU94T2VOMlFSbXJpeGdYN2lvQ3NESHJaMkNZQWJ4WThOaHROa0xxM0UzNkYKVlY5RnBlOUFXS3E1ZzFJQnNKOFFFa0tJTHUvQ0lwTT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: voiyd-certs
  namespace: voiyd
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: voiyd-server
  name: voiyd-server
  namespace: voiyd
spec:
  ports:
    - name: grpc
      port: 5743
      protocol: TCP
      targetPort: 5743
    - name: gateway
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: voiyd-server
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: voiyd-server
  name: voiyd-server
  namespace: voiyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiyd-server
  strategy: {}
  template:
    metadata:
      labels:
        app: voiyd-server
    spec:
      volumes:
        - name: certs
          secret:
            secretName: voiyd-certs
        - name: data
          emptyDir: {}
      containers:
        - image: ghcr.io/amimof/voiyd:latest
          imagePullPolicy: Always
          args:
            - "voiyd-server"
            - "--log-level=debug"
            - "--tls-certificate=/etc/voiyd/tls/tls.crt"
            - "--tls-key=/etc/voiyd/tls/tls.key"
            - "--tls-host=0.0.0.0"
            - "--server-address=0.0.0.0:5743"
            - "--gateway-server=0.0.0.0:8443"
            - "--metrics-server=0.0.0.0:8888"
          name: server
          ports:
            - name: grpc
              containerPort: 5743
            - name: gateway
              containerPort: 8443
            - name: metrics
              containerPort: 8888
          volumeMounts:
            - name: certs
              mountPath: /etc/voiyd/tls
            - name: data
              mountPath: /var/lib/voiyd
          resources: {}
