---
apiVersion: v1
kind: Secret
metadata:
  name: voiyd-server-tls
  namespace: voiyd
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFmzCCA4OgAwIBAgIUNGm7f0tX6fX8+1bqEp3qA1LGQQMwDQYJKoZIhvcNAQEL
    BQAwXTELMAkGA1UEBhMCU0UxDzANBgNVBAgMBkV1cm9wZTESMBAGA1UEBwwJU3Rv
    Y2tob2xtMQ4wDAYDVQQKDAV2b2l5ZDEUMBIGA1UECwwLZTJlLXRlc3RpbmcxDzAN
    BgNVBAMMBnNlcnZlcjAeFw0yNTAxMjMwMDAwMDBaFw0yNjAxMjMwMDAwMDBaMF0x
    CzAJBgNVBAYTAlNFMQ8wDQYDVQQIDAZFdXJvcGUxEjAQBgNVBAcMCVN0b2NraG9s
    bTEOMA== 
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCgKCAgEAw5xqN9bH8KOy2zQF9VQJYJrK
    m0pN6fH8mH0v3pE1gD5bN4pQE0qGKvL8nD6jD7hL9kD5bN4pQE0qGKvL8nD6FAKE
    -----END PRIVATE KEY-----
