---
apiVersion: v1
kind: Service
metadata:
  name: voiyd-server
  namespace: voiyd
  labels:
    app: voiyd-server
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 5743
      protocol: TCP
      targetPort: 5743
    - name: gateway
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: voiyd-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voiyd-server
  namespace: voiyd
  labels:
    app: voiyd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voiyd-server
  template:
    metadata:
      labels:
        app: voiyd-server
    spec:
      volumes:
        - name: certs
          secret:
            secretName: voiyd-server-tls
        - name: data
          emptyDir: {}
      containers:
        - name: server
          image: ghcr.io/amimof/voiyd:e2e-test
          imagePullPolicy: IfNotPresent
          args:
            - "voiyd-server"
            - "--log-level=debug"
            - "--tls-certificate=/etc/voiyd/tls/tls.crt"
            - "--tls-key=/etc/voiyd/tls/tls.key"
            - "--tls-host=0.0.0.0"
            - "--tcp-tls-host=0.0.0.0"
            - "--metrics-host=0.0.0.0"
          ports:
            - name: grpc
              containerPort: 5743
            - name: gateway
              containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /etc/voiyd/tls
            - name: data
              mountPath: /var/lib/voiyd
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
