---
apiVersion: v1
kind: Service
metadata:
  name: voiyd-node
  namespace: voiyd
  labels:
    app: voiyd-node
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    app: voiyd-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voiyd-node
  namespace: voiyd
  labels:
    app: voiyd-node
spec:
  replicas: 3
  serviceName: voiyd-node
  selector:
    matchLabels:
      app: voiyd-node
  template:
    metadata:
      labels:
        app: voiyd-node
    spec:
      shareProcessNamespace: true
      volumes:
        - name: data
          emptyDir: {}
        - name: containerd-storage
          emptyDir: {}
        - name: docker-storage
          emptyDir: {}
        - name: containerd-sock
          emptyDir: {}
      containers:
        - name: containerd
          image: docker:29-dind
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          volumeMounts:
            - name: containerd-storage
              mountPath: /var/lib/containerd
            - name: docker-storage
              mountPath: /var/lib/docker
            - name: containerd-sock
              mountPath: /var/run/docker/containerd
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
        - name: node
          image: ghcr.io/amimof/voiyd:e2e-test
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
          args:
            - "voiyd-node"
            - "--port=5743"
            - "--host=voiyd-server"
            - "--log-level=debug"
            - "--insecure-skip-verify"
            - "--metrics-host=0.0.0.0"
          ports:
            - name: metrics
              containerPort: 8889
          volumeMounts:
            - name: data
              mountPath: /var/lib/voiyd
            - name: containerd-sock
              mountPath: /run/containerd
            - name: containerd-storage
              mountPath: /var/lib/containerd
            - name: docker-storage
              mountPath: /var/lib/docker
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
