kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: voiyd-e2e
nodes:
  - role: control-plane
  - role: worker
    labels:
      voiyd-node: "node-1"
  - role: worker
    labels:
      voiyd-node: "node-2"
  - role: worker
    labels:
      voiyd-node: "node-3"
networking:
  # Disable default CNI so we can test voiyd's networking
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
