name: Publish

on:
  release:
    types: [published]

jobs:
  homebrew:
    runs-on: ubuntu-24.04
    name: homebrew-releaser
    steps:
      - name: Release project to Homebrew tap
        uses: Justintime50/homebrew-releaser@v3
        with:
          homebrew_owner: amimof
          homebrew_tap: homebrew-voiyd
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          install: 'bin.install Dir["voiydctl-*"].first => "voiydctl"'
